os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: 0.10.40
      msvs_toolset: 14
    - nodejs_version: 0.12.7
      msvs_toolset: 14

platform:
  - x64
  - x86

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
